---
# This 

- name: pagespeed | Create temporary directory
  shell: mktemp -d
  register: tempdir
  sudo: true
  tags: pagespeed_setup

- name: pagespeed | Download pagespeed
  get_url:
    url="{{pagespeed_url}}"
    dest="{{ pagespeed_dir_tmp }}/"
  register: pagespeed_download
  tags: pagespeed_setup

- name: pagespeed | Add package
  apt: deb={{ pagespeed_dir_tmp }}/{{ pagespeed_package_deb }}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  when: pagespeed_download.changed  
  tags: pagespeed_setup
  
#- name: pagespeed | Install package
#  action: command apt-get -f install
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#  tags: pagespeed_setup
  
- name: pagespeed | Cleanup temporary directory
  file: name={{ tempdir.stdout }} state=absent
  tags: pagespeed_setup

- debug: msg=" pagespeed | See statisctics at http://localhost/pagespeed_console"
